### ISSUE TITLE
`distribution` assumes we are collecting a histogram of time

### ISSUE THREAD

**Issue by dantswain** [beam-telemetry/telemetry_metrics_prometheus_core#21]
Hi!   I'm trying to collect a histogram of the size in bytes of a piece of data in addition to some other timing metrics.  When I do this I get warnings about both inconsistent units and not using seconds.  This seems incorrect to me as I'm collecting something that's not time-based.  I'm relatively new to Prometheus but AFAICT it's not unexpected to use the histogram metric type to collect non-timing data.

As an example:

```
def metrics do
  [
       distribution("my_app.response_sent.body_size",
        buckets: [0.1, 1.0, 10.0],
        unit: {:byte, :kilobyte}
      ),
      distribution("my_app.response_sent.duration",
        buckets: [0.01, 0.1, 1.0, 10.0],
        unit: :second
      )
  ]
end
```

This results in the following warning logs:
```
15:30:10.285 [warn] Multiple time units found in your Telemetry.Metrics definitions.

Prometheus recommends using consistent time units to make view creation simpler.

You can disable this validation check by adding `consistent_units: false` in the validations options on reporter init.
15:30:10.285 [warn] Prometheus requires that time units MUST only be offered in seconds according to their guidelines, though this is not always practical.

https://prometheus.io/docs/instrumenting/writing_clientlibs/#histogram.

You can disable this validation check by adding `require_seconds: false` in the validations options on reporter init.
```

On the whole, I appreciate the warnings, so it would be nice to be able to maybe disable them at an individual metric level?

**Comment by bryannaegele** [comment]
@dantswain it looks like we just need to add support for the bytes conversion to the validator. Right now it only handles time when it sees a tuple on the unit. There would also be a false positive if you used any other unit, such as `:each`. I think we can support the warning for time and size but ignore anything else in that particular validation.
