### ISSUE TITLE
Complete transfer to beam-telemetry org

### ISSUE THREAD

**Issue by bryannaegele** [beam-telemetry/telemetry_metrics_prometheus_core#7]
TODO:

- [ ] Update mix file repo refs
- [ ] Update readme repo refs
- [ ] Add a second maintainer

**Comment by bryannaegele** [comment]
@josevalim should we move these to consistent namespaces, e.g. `Telemetry.Metrics.Prometheus` vs the current `TelemetryMetricsPromethus`? @arkgil and I put this and the statsd reporter under a single namespace (probably shouldn't have done that). 

I didn't know at the time I wrote this that people did put things under the same namespace, e.g. PlugCowboy namespacing under `Plug` as `Plug.Cowboy`.

I'd like to get the last of the breaking changes out in the next release.

**Comment by josevalim** [comment]
Theoretically we should not write to the namespace of other packaages, even if we own them all, so I would say the current name is correct.
